spring:
   data:
      mongodb:
         host: localhost
         port: 27017
         username: user
         password: passwd
         database: oauth-db
server:
   servlet:
      context-path: /uaa
   port: 8081